### ISSUE TITLE
job advertisements

### ISSUE THREAD

**Issue by pika-80** [Concept-Collective/cc-chat#14]
create a command for the police to make announcements for civilians to see

**Comment by Jye-AU** [comment]
Thank you for your interest in adding a new feature to CC Chat. However, I regret to inform you that we will not be able to implement this feature as it goes against our design principles.

In CC Chat, commands are added by server developers rather than being a part of the resource itself. This approach enables developers to have more control over the commands and ensures that they are tailored to the specific needs of their server.

While we appreciate your suggestion, we believe that this approach is the best way to maintain the quality and functionality of CC Chat.
